"""'wallet_added2'

Revision ID: 145c4c8ddb64
Revises: 4c9f3d7edb3d
Create Date: 2024-08-05 11:42:25.811869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '145c4c8ddb64'
down_revision = '4c9f3d7edb3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incentive', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('deduction', mysql.DECIMAL(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.drop_column('deduction')
        batch_op.drop_column('incentive')

    # ### end Alembic commands ###
