"""pickup km added

Revision ID: 1b5d1f25fbdc
Revises: d571f60f608b
Create Date: 2024-07-11 18:20:41.101704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5d1f25fbdc'
down_revision = 'd571f60f608b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_km', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.drop_column('pickup_km')

    # ### end Alembic commands ###
