"""'payment_type_added'

Revision ID: 34277aad148d
Revises: a28c3ffaea7f
Create Date: 2024-08-04 15:07:46.536336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34277aad148d'
down_revision = 'a28c3ffaea7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###
