"""'wallet_updated'

Revision ID: abe7480fa6ac
Revises: d97dc1d43216
Create Date: 2024-08-05 13:25:01.023791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abe7480fa6ac'
down_revision = 'd97dc1d43216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ride_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.drop_column('from_date')
        batch_op.drop_column('to_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_date', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('from_date', mysql.DATETIME(), nullable=False))
        batch_op.drop_column('date')
        batch_op.drop_column('ride_id')

    # ### end Alembic commands ###
