"""'salary_status_added'

Revision ID: d97dc1d43216
Revises: 0c7a416703c3
Create Date: 2024-08-05 12:31:12.557429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97dc1d43216'
down_revision = '0c7a416703c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.drop_column('salary_status')

    # ### end Alembic commands ###
