"""liveloc added

Revision ID: dbde825ae0ef
Revises: 1b5d1f25fbdc
Create Date: 2024-07-11 21:46:27.625704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbde825ae0ef'
down_revision = '1b5d1f25fbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liveloc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(length=200), nullable=True),
    sa.Column('longitude', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liveloc')
    # ### end Alembic commands ###
